id = "yuga"
name = "Yuga"
version = "0.1.11"
schema_version = 1
authors = ["Yuga"]
description = "Yuga language: syntax highlighting and diagnostics via yuga-lsp"

[grammars.yuga]
repository = "file:///Users/bala_mani/Documents/yuga/packages/tree-sitter-yuga"
rev = "70a801cee9ab69e4eca5817f21607a98365d7479"

[language_servers.yuga-lsp]
name = "Yuga LSP"
language = "Yuga"
languages = ["Yuga"]

[language_servers.yuga-lsp.language_ids]
Yuga = "yuga"
