#!/bin/sh
# Install JDK, Android SDK/NDK, Gradle, and an emulator AVD for this example.
# Idempotent. macOS + Homebrew. Writes .sdk-env next to this script for run.sh.
set -e
HERE=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
ENV_FILE=$HERE/.sdk-env
API=34
NDK=26.3.11579264
BUILD_TOOLS=34.0.0
AVD_NAME=yuga

die() {
  echo "install.sh: $*" >&2
  exit 1
}

if [ "$(uname -s)" != Darwin ]; then
  die "this script is for macOS (Homebrew). Install the Android SDK on this OS, then set ANDROID_HOME."
fi
command -v brew >/dev/null 2>&1 || die "Homebrew is required: https://brew.sh"

echo "android: JDK"
if ! /usr/libexec/java_home >/dev/null 2>&1; then
  brew install --cask temurin
fi
JAVA_HOME=$(/usr/libexec/java_home) || die "no JDK after Temurin install"
export JAVA_HOME

echo "android: Gradle"
if ! command -v gradle >/dev/null 2>&1; then
  brew install gradle
fi

echo "android: command-line tools"
if ! brew list --cask android-commandlinetools >/dev/null 2>&1; then
  brew install --cask android-commandlinetools
fi

write_env() {
  {
    echo "# generated by zeus/examples/counter/android/install.sh"
    echo "export JAVA_HOME=\"$JAVA_HOME\""
    echo "export ANDROID_HOME=\"$ANDROID_HOME\""
    echo "export ANDROID_SDK_ROOT=\"$ANDROID_HOME\""
    echo "export PATH=\"\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/emulator:\$PATH\""
  } > "$ENV_FILE"
}

BREW_SDK=$(brew --prefix)/share/android-commandlinetools
if [ -n "$ANDROID_HOME" ] && [ -d "$ANDROID_HOME" ]; then
  :
elif [ -n "$ANDROID_SDK_ROOT" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
  ANDROID_HOME=$ANDROID_SDK_ROOT
elif [ -d "$HOME/Library/Android/sdk" ]; then
  ANDROID_HOME=$HOME/Library/Android/sdk
elif [ -d "$BREW_SDK" ]; then
  ANDROID_HOME=$BREW_SDK
else
  die "could not find an SDK root after installing android-commandlinetools"
fi
export ANDROID_HOME
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
write_env
echo "android: wrote $ENV_FILE"

SDKMANAGER=
if [ -x "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
  SDKMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
elif command -v sdkmanager >/dev/null 2>&1; then
  SDKMANAGER=$(command -v sdkmanager)
else
  die "sdkmanager not found under $ANDROID_HOME"
fi

echo "android: SDK root $ANDROID_HOME"
echo "android: accepting licenses"
yes | "$SDKMANAGER" --sdk_root="$ANDROID_HOME" --licenses >/dev/null || true

ARCH=$(uname -m)
case "$ARCH" in
  arm64|aarch64) ABI=arm64-v8a ;;
  *) ABI=x86_64 ;;
esac
SYSIMG="system-images;android-$API;google_apis;$ABI"

echo "android: platforms / NDK / emulator ($ABI)"
"$SDKMANAGER" --sdk_root="$ANDROID_HOME" \
  "platform-tools" \
  "platforms;android-$API" \
  "build-tools;$BUILD_TOOLS" \
  "ndk;$NDK" \
  "emulator" \
  "$SYSIMG"

AVDMANAGER=$ANDROID_HOME/cmdline-tools/latest/bin/avdmanager
if [ ! -x "$AVDMANAGER" ]; then
  AVDMANAGER=$(command -v avdmanager 2>/dev/null || true)
fi
if [ -z "$AVDMANAGER" ] || [ ! -x "$AVDMANAGER" ]; then
  die "avdmanager not found"
fi

if ! "$AVDMANAGER" list avd 2>/dev/null | grep -q "^[[:space:]]*Name:[[:space:]]*$AVD_NAME$"; then
  echo "android: creating AVD $AVD_NAME"
  echo no | "$AVDMANAGER" create avd --force \
    --name "$AVD_NAME" \
    --package "$SYSIMG" \
    --device pixel_6 >/dev/null
else
  echo "android: AVD $AVD_NAME already exists"
fi

# Host GPU often fails on macOS (ERROR 12299/12301, blank window).
ini=$HOME/.android/avd/${AVD_NAME}.avd/config.ini
if [ -f "$ini" ]; then
  tmp=$ini.tmp
  grep -v '^hw.gpu.mode=' "$ini" | grep -v '^hw.gpu.enabled=' > "$tmp"
  printf 'hw.gpu.enabled=yes\nhw.gpu.mode=swiftshader_indirect\n' >> "$tmp"
  mv "$tmp" "$ini"
  echo "android: AVD GPU = swiftshader_indirect"
fi

write_env

echo
echo "android: done"
echo "  ANDROID_HOME=$ANDROID_HOME"
echo "  JAVA_HOME=$JAVA_HOME"
echo "  AVD=$AVD_NAME"
echo "  env written to $ENV_FILE (sourced by run.sh)"
echo
echo "Optional: add the export lines from $ENV_FILE to ~/.zshrc"
echo "Then: $HERE/run.sh"
echo "  (start the emulator first: emulator -avd $AVD_NAME )"
