#!/bin/sh
# Android emulator UI. Starts the gRPC-Web backend on :8080 if it is not up.
# Emulator reaches the Mac loopback at 10.0.2.2, not 127.0.0.1.
set -e
HERE=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
d=$HERE
REPO=
BACK_PID=
STARTED_BACK=0

cleanup() {
  if [ "$STARTED_BACK" = 1 ] && [ -n "$BACK_PID" ]; then
    kill "$BACK_PID" 2>/dev/null || true
    wait "$BACK_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

while [ "$d" != / ]; do
  if [ -f "$d/Makefile" ] && [ -d "$d/packages/compiler/src" ]; then
    REPO=$d
    break
  fi
  d=$(CDPATH= cd -- "$d/.." && pwd)
done
if [ -z "$REPO" ]; then
  echo "run.sh: could not find the yuga repo (Makefile + packages/compiler/src/)" >&2
  exit 1
fi
if [ -f "$HERE/.sdk-env" ]; then
  # Generated by ./install.sh (JAVA_HOME, ANDROID_HOME, PATH).
  # shellcheck disable=SC1091
  . "$HERE/.sdk-env"
fi
if [ -z "$ANDROID_HOME" ] || [ ! -d "$ANDROID_HOME" ]; then
  if [ -n "$ANDROID_SDK_ROOT" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
    ANDROID_HOME=$ANDROID_SDK_ROOT
  elif [ -d "$HOME/Library/Android/sdk" ]; then
    ANDROID_HOME=$HOME/Library/Android/sdk
  elif command -v brew >/dev/null 2>&1 && [ -d "$(brew --prefix)/share/android-commandlinetools" ]; then
    ANDROID_HOME=$(brew --prefix)/share/android-commandlinetools
  fi
  export ANDROID_HOME
fi
if [ -z "$ANDROID_HOME" ] || [ ! -d "$ANDROID_HOME" ]; then
  echo "run.sh: no Android SDK. Install it first (that also creates .sdk-env):" >&2
  echo "  $HERE/install.sh" >&2
  exit 1
fi
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
if [ -z "$JAVA_HOME" ] && [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null || true)
  [ -n "$JAVA_HOME" ] && export JAVA_HOME
fi

if [ ! -x "$REPO/bin/yugac" ]; then
  echo "run.sh: building yugac"
  make -C "$REPO" -j4
fi

# No device or emulator connected? Boot the shared 'yuga' AVD so a fresh
# user gets a clear flow instead of gradle's 'No connected devices!'.
if ! adb get-state 2>/dev/null | grep -q device; then
  EMU=$ANDROID_HOME/emulator/emulator
  if [ ! -x "$EMU" ]; then
    echo "android: no device connected and no emulator installed. Install the" >&2
    echo "  SDK stack once ($HERE/install.sh), then boot the emulator:" >&2
    echo "  $HERE/emu.sh" >&2
    exit 1
  fi
  echo "android: no device connected — booting the 'yuga' emulator"
  "$EMU" -avd yuga -gpu swiftshader_indirect -feature -Vulkan \
    -no-snapshot-load -no-boot-anim >/dev/null 2>&1 &
  n=0
  while [ "$n" -lt 240 ]; do
    if [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" = 1 ]; then
      break
    fi
    n=$((n + 1))
    sleep 1
  done
  if [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != 1 ]; then
    echo "android: emulator did not finish booting in 240 s — check $HERE/emu.sh" >&2
    exit 1
  fi
  echo "android: emulator ready (left running; stop it later with: adb emu kill)"
fi

if ! nc -z 127.0.0.1 8080 >/dev/null 2>&1; then
  echo "android: starting backend on :8080"
  "$HERE/../backend/run.sh" &
  BACK_PID=$!
  STARTED_BACK=1
  n=0
  while [ "$n" -lt 80 ]; do
    if nc -z 127.0.0.1 8080 >/dev/null 2>&1; then
      break
    fi
    if ! kill -0 "$BACK_PID" 2>/dev/null; then
      echo "run.sh: backend exited before it listened on :8080" >&2
      exit 1
    fi
    n=$((n + 1))
    sleep 0.1
  done
  if [ "$n" -ge 80 ]; then
    echo "run.sh: timed out waiting for backend on :8080" >&2
    exit 1
  fi
fi

echo "android: emulator  (RPC http://10.0.2.2:8080 → host :8080)"
exec "$REPO/bin/yugac" --target=android --run "$HERE/app.yuga"
