#!/bin/sh
# Android emulator UI for the zeus gallery (pure UI: no backend needed).
set -e
HERE=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
d=$HERE
REPO=
while [ "$d" != / ]; do
  if [ -f "$d/Makefile" ] && [ -d "$d/packages/compiler/src" ]; then
    REPO=$d
    break
  fi
  d=$(CDPATH= cd -- "$d/.." && pwd)
done
if [ -z "$REPO" ]; then
  echo "run.sh: could not find the yuga repo (Makefile + packages/compiler/src/)" >&2
  exit 1
fi
if [ -f "$HERE/.sdk-env" ]; then
  # Generated by ./install.sh (JAVA_HOME, ANDROID_HOME, PATH).
  # shellcheck disable=SC1091
  . "$HERE/.sdk-env"
fi
if [ -z "$ANDROID_HOME" ] || [ ! -d "$ANDROID_HOME" ]; then
  if [ -n "$ANDROID_SDK_ROOT" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
    ANDROID_HOME=$ANDROID_SDK_ROOT
  elif [ -d "$HOME/Library/Android/sdk" ]; then
    ANDROID_HOME=$HOME/Library/Android/sdk
  elif command -v brew >/dev/null 2>&1 && [ -d "$(brew --prefix)/share/android-commandlinetools" ]; then
    ANDROID_HOME=$(brew --prefix)/share/android-commandlinetools
  fi
  export ANDROID_HOME
fi
if [ -z "$ANDROID_HOME" ] || [ ! -d "$ANDROID_HOME" ]; then
  echo "run.sh: no Android SDK. Install it first (that also creates .sdk-env):" >&2
  echo "  $HERE/install.sh" >&2
  exit 1
fi
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH"
if [ -z "$JAVA_HOME" ] && [ -x /usr/libexec/java_home ]; then
  JAVA_HOME=$(/usr/libexec/java_home 2>/dev/null || true)
  [ -n "$JAVA_HOME" ] && export JAVA_HOME
fi

if [ ! -x "$REPO/bin/yugac" ]; then
  echo "run.sh: building yugac"
  make -C "$REPO" -j4
fi

echo "android: emulator (pure UI, no backend)"
exec "$REPO/bin/yugac" --target=android --run "$HERE/app.yuga"
